### ISSUE TITLE
[DATASET GROUPS] Filtering by created date latest first & oldest first doesn't work

### ISSUE THREAD

**Issue by vaunapuu** [buerokratt/Classifier#162]
PRECONDITIONS: Several dataset groups with different times during the same day

Steps to Reproduce:
1. Pick Created Date Latest First OR oldest first
2. Click on Search 

Expected Result:
All results are filtered according to Last Updated time

Actual Result: 
Results are not filtered according to last Updated time
<img width="1461" alt="Screenshot 2024-10-13 at 14 38 43" src="https://github.com/user-attachments/assets/91fe6006-3d4c-4011-ac14-c17c6187ee31">

**Comment by Kristjan259** [comment]
Seems to work, although can be confusing to test since the only last updated is shown and not created date.
