### ISSUE TITLE
[CREATE DATASET GROUPS] rowid can used as field name

### ISSUE THREAD

**Issue by vaunapuu** [buerokratt/Classifier#164]
PRECONDITIONS:
Existing dataset group created

Steps to Reproduce:
Open Settings for a dataset group
Go to Field Name
Edit field name to rowid
Click 'Save'

Expected Result:
Error message

Actual Result:
rowid is accepted
<img width="1446" alt="Screenshot 2024-10-13 at 15 46 40" src="https://github.com/user-attachments/assets/9ab61cac-d4d0-4987-9101-d7ca3c98752b">

**Comment by Kristjan259** [comment]
Cannot use rowid as a field name anymore.

![Screenshot 2024-11-13 at 19 16 54](https://github.com/user-attachments/assets/b15203eb-5ea2-4731-929a-a2f9480386ee)
